### ISSUE TITLE
Unable to update from 1.2.0 to 1.2.1 automatically on Ubuntu 14.04

### ISSUE THREAD

**Issue by MagnusS** [ocaml/0install-tools#1]
```
$ opam --version
1.2.0

$ 0install update opam
A later version (OPAM 1.2.2-rc1) exists but was not selected. Using 1.2.0 instead.
To select "testing" versions, use:
0install config help_with_testing True

$ 0install update opam --version=1.2.1
http://tools.ocaml.org/opam.xml: 1.2.0 -> 1.2.1
A later version (OPAM 1.2.2-rc1) exists but was not selected. Using 1.2.1 instead.
To select "testing" versions, use:
0install config help_with_testing True

$ opam --version
1.2.1
```

**Comment by talex5** [comment]
1.2.1 is buggy (esp. with fish shell), so it's still marked as "testing" in 0install. 1.2.2-rc1 seems to be working, but was only released a few days ago, so also still "testing". I'm tempted to mark it as stable though, as it seems fine.

**Comment by avsm** [comment]
there are some semantic changes in repository interpretation (flags:depext) in 1.2.2-rc2 (due soon), so would be better not to release rc1 too widely in the wild. /cc @AltGr

**Comment by MagnusS** [comment]
Ah ok. Homebrew updates to opam 1.2.1 automatically, so I thought it was stable.

**Comment by avsm** [comment]
1.2.1 is stable, but its interface to the 0install packaging had some issues

**Comment by talex5** [comment]
It's not just the external solver issue; there's also:
* https://github.com/ocaml/opam/issues/2070 - opam 1.2.1 with fish breaks man command
* https://github.com/ocaml/opam/issues/2063 `opam config env` no longer works on fish with 1.2.1

Anyway, I'll leave 1.2.0 as the stable version for now.

**Comment by talex5** [comment]
Closing, as we have 1.2.2 in the repository now (as well as 2.0.1 and 2.0.3).
